Boekingssysteem/Models/Richting.cs
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Boekingssysteem.Models
{
    public class Richting
    {
        public int RichtingID { get; set; }

        [Required(ErrorMessage = "Naam moet ingevuld zijn!")]
        public string Naam { get; set; }

        //Navigatieproperty
        public virtual ICollection<PersoonRichting> PersoonRichtingen { get; set; }
    }
}

Boekingssysteem/Controllers/RichtingController.cs
using Boekingssysteem.Data;
using Boekingssysteem.Lib;
using Boekingssysteem.Models;
using Boekingssysteem.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Xml.Linq;

namespace Boekingssysteem.Controllers
{
    [Authorize(Roles = "admin")]
    public class RichtingController : Controller
    {
        private readonly BoekingssysteemContext _context;

        public RichtingController(BoekingssysteemContext context)
        {
            _context = context;
        }

        public ViewResult Index()
        {
            return View();
        }

        public IActionResult Toevoegen()
        {
            ViewBag.Visibility = "invisible";
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Toevoegen(RichtingCRUDViewModel viewModel)
        {
            var richtingen = _context.Richtingen.ToList();
            viewModel.Richtingen = richtingen;

            foreach (var functie in viewModel.Richtingen)
            {
                if (viewModel.Naam.ToLower() == functie.Naam.ToLower())
                {
                    ViewBag.Class = "alert alert-danger mb-5";
                    ViewBag.Visibility = "visible";

                    return View(viewModel);
                }
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Add(new Richting()
                    {
                        Naam = viewModel.Naam,
                    });

                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
                catch (Exception ex)
                {
                    Foutenlogboek.FoutLoggen(ex);
                }

            }
            return View(viewModel);
        }

        public IActionResult Overview()
        {
            RichtingCRUDViewModel viewModel = new RichtingCRUDViewModel();
            var lijstRichtingen = _context.Richtingen.ToList();
            viewModel.lijstRichtingen = lijstRichtingen;

            //ViewBag.Visibility = "invisible";
            return View(viewModel);
        }

        public async Task<IActionResult> Aanpassen(int? id)
        {
            if (id == null)
                return NotFound();

            Richting richting = _context.Richtingen.Where(d => d.RichtingID == id).FirstOrDefault();

            if (richting == null)
                return NotFound();

            RichtingCRUDViewModel vm = new RichtingCRUDViewModel()
            {
                RichtingID = richting.RichtingID,
                Naam = richting.Naam
            };

            return View(vm);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Aanpassen(int id, RichtingCRUDViewModel viewModel)
        {
            if (id != viewModel.RichtingID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    Richting richting = new Richting()
                    {
                        RichtingID = viewModel.RichtingID,
                        Naam = viewModel.Naam
                    };
                    _context.Update(richting);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException e)
                {
                    if (!_context.Richtingen.Any(d => d.RichtingID == viewModel.RichtingID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(viewModel);
        }

        public async Task<IActionResult> Verwijderen(int id)
        {
            Richting richting = _context.Richtingen.Where(d => d.RichtingID == id).FirstOrDefault();
            if (richting != null)
            {
                RichtingCRUDViewModel vm = new RichtingCRUDViewModel()
                {
                    RichtingID = id,
                    Naam = richting.Naam
                };
            }

            _context.Richtingen.Remove(richting);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Overview));
        }
    }
}

Boekingssysteem/Views/Richting/Aanpassen.cshtml
@model Boekingssysteem.ViewModels.RichtingCRUDViewModel

@{
    ViewData["Title"] = "Aanpassen";
}

<a class="btn btn-primary btn-lg mb-5" asp-controller="Richting" asp-action="Index">Terug</a>
<hr />

<form asp-action="Aanpassen">
    <input type="hidden" asp-for="RichtingID" />
    <div class="row mt-5">
        <div asp-validation-summary="ModelOnly" class="text-danger" />
        <div class="col-md-6">
            <div class="form-group">
                <label asp-for="Naam" class="control-label">@Html.DisplayNameFor(model => this.Model.Naam)</label>
                <input asp-for="Naam" class="form-control" />
                <span asp-validation-for="Naam" class="text-danger"></span>
                <div class="form-group ml-2">
                    <input type="submit" value="Aanpassen" class="btn btn-primary mt-2 mb-2" />
                </div>
            </div>
        </div>        
    </div>
</form>

Boekingssysteem/Views/Richting/Index.cshtml
@{
    ViewData["Title"] = "Richtingbeheer";
}

<a class="btn btn-primary btn-lg mb-5" asp-controller="Home" asp-action="AdminView">Terug</a>
<hr />
<div class="h-100 d-flex align-items-center justify-content-center">
    <div BtnCrud>
        <div class="col">
            <div class="mb-5">
                <a asp-controller="Richting" asp-action="Toevoegen" class="btn btn-primary btn-lg mb-2" role="button">Richting aanmaken</a>
            </div>
            <div class="mb-5">
                <a asp-controller="Richting" asp-action="Overview" class="btn btn-primary btn-lg mb-2" role="button">Richting wijzigen/verwijderen</a>
            </div>
        </div>
    </div>
</div>

Boekingssysteem/Views/Richting/Overview.cshtml
@model Boekingssysteem.ViewModels.RichtingCRUDViewModel

@{
    ViewData["Title"] = "Overview";
}

<a class="btn btn-primary btn-lg mb-5" asp-controller="Richting" asp-action="Index">Terug</a>
<hr />

<table class="table table-bordered table-striped">
    <tr>
        <th>@Html.DisplayNameFor(model => model.lijstRichtingen[0].Naam)</th>
        <th></th>
        <th></th>
        <th></th>
    </tr>
    @foreach (var functie in Model.lijstRichtingen)
    {
        <tr>
            <td>@functie.Naam</td>
            <td><a class="button" asp-action="Aanpassen" asp-route-id="@functie.RichtingID">Aanpassen</a></td>
            <td><a class="button" asp-action="Verwijderen" asp-route-id="@functie.RichtingID">Verwijderen</a></td>
        </tr>
    }
</table>

Boekingssysteem/Views/Richting/Toevoegen.cshtml
@model Boekingssysteem.ViewModels.RichtingCRUDViewModel

@{
    ViewData["Title"] = "Richtingbeheer";
}

<a class="btn btn-primary btn-lg mb-5" asp-controller="Richting" asp-action="Index">Terug</a>
<hr />

<div class="h-100 d-flex align-items-center justify-content-center">
    <div BtnCrud>
        <div class="col-sm-12">
            <div class="mb-5">
                <form asp-action="Toevoegen">
                    <div class="@ViewBag.Class @ViewBag.Visibility" role="alert">
                        Deze functie bestaat al!
                    </div>
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group row">
                        <label asp-for="Naam" class="col-sm-4 col-form-label">Naam</label>
                        <div class="col-sm-10">
                            <input asp-for="Naam" class="form-control" id="Naam" placeholder="">
                            <span asp-validation-for="Naam" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-sm-10">
                            <button type="submit" value="Toevoegen" class="btn btn-primary mt-4">Toevoegen</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}